import { Product } from './types/Product';
const products: Product[] = [
  {
    _id: '1',
    name: 'Flory Woman Dress',
    image: '/images/d.png',
    description: 'Frill Trim Ruched Bust Sunflower Print Dress, White color',
    brand: 'Shein',
    category: 'Dresses',
    price: 'US$8.00',
    countInStock: 4,
    rating: 4.3,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Sunglasses',
    image: '/images/glasses.png',
    description: 'Rhinestone Decor Sunglasses',
    brand: 'Shein',
    category: 'Glasses',
    price: 'US$4.00',
    countInStock: 8,
    rating: 3.7,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Hair Crown',
    image: '/images/hairPiece.png',
    description: 'Pearl Leaves Hair Crown Piece',
    brand: 'Shein',
    category: 'Hair-Accessories',
    price: 'US$6.00',
    countInStock: 2,
    rating: 4.7,
    numReviews: 14,
  },
  {
    _id: '4',
    name: 'Brushs',
    image: '/images/brush.png',
    description: '10pcs White Makeup Brushes',
    brand: 'Shein',
    category: 'Makeup-Tools',
    price: 'US$10.00',
    countInStock: 4,
    rating: 3.9,
    numReviews: 10,
  },
  {
    _id: '5',
    name: 'Mirror',
    image: '/images/mirror.png',
    description: 'Cat Ears Modren Mirror',
    brand: 'Shein',
    category: 'Accessories',
    price: 'US$3.00',
    countInStock: 5,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '6',
    name: 'Hair Piece',
    image: '/images/hairPiece2.png',
    description: 'Elegant Pearl Hair Piece',
    brand: 'Shein',
    category: 'Hair-Accessories',
    price: 'US$5.00',
    countInStock: 3,
    rating: 4.5,
    numReviews: 15,
  },
  {
    _id: '7',
    name: 'Brush Bucket',
    image: '/images/bucket.png',
    description: 'Decorated Bucket for storing Makeup burshes',
    brand: 'Shein',
    category: 'Makeup',
    price: 'US$3.00',
    countInStock: 12,
    rating: 3.6,
    numReviews: 7,
  },
];

export default products;
